#!/usr/bin/env python3
"""
Generate two-panel null injection test figure for Paper 3.

Panel (a): Per-realization false-positive rate — strict cap vs relaxed cap
Panel (b): Hill criterion scatter — FP shells vs real shells

Inputs (from data/processed/):
  - null_test_results.csv      (output of run_null_test.py)
  - sparc_relaxed_caps_with_BH_decomp.csv  (real catalog, for Burkert params)

Outputs (to figures/paper/):
  - null_test_figure.pdf
  - null_test_figure.png

Usage:
  python scripts/plot_null_test.py
  python scripts/plot_null_test.py --no-pdf

Author: Ron Bibb (generated by Claude)
Date: 2026-05-23
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import argparse
import os

# ============================================================================
# CONFIGURATION
# ============================================================================

NULL_CSV   = 'data/processed/null_test_results.csv'
REAL_CSV   = 'data/processed/sparc_relaxed_caps_with_BH_decomp.csv'
OUTPUT_DIR = 'figures/paper'

G = 4.302e-6   # kpc (km/s)^2 / M_sun

# Colours
C04   = '#2C6FAC'   # steel blue   — strict cap
C08   = '#D95F02'   # burnt orange — relaxed cap
CGREY = '#888888'   # mid-grey     — real shells

# ============================================================================
# PHYSICS
# ============================================================================

def burkert_M_enc(r, rho_0, a):
    """Burkert enclosed mass within r (M_sun)."""
    a = max(float(a), 1e-6)
    x = r / a
    return np.pi * rho_0 * a**3 * (
        np.log(1 + x**2) + 2 * np.log(1 + x) - 2 * np.arctan(x))

# ============================================================================
# DATA LOADING
# ============================================================================

def load_null(path):
    df = pd.read_csv(path)
    fp = df[(df['false_positive'] == 1) & df['hill_ratio'].notna()].copy()
    return df, fp


def load_real_shells(path):
    """
    Extract real shells from the relaxed-cap catalog and compute the
    physically correct Hill ratio: M_shell / M_burkert_enc(r_shell).
    """
    real = pd.read_csv(path)
    rows = []
    for _, g in real.iterrows():
        n    = int(g['fw_best_n_shells'])
        rho0 = float(g['burk_rho0'])
        a    = float(g['burk_a_kpc'])
        for i in range(1, n + 1):
            r_sh = g.get(f'shell{i}_r_kpc')
            M_sh = g.get(f'shell{i}_M')
            sig  = g.get(f'shell{i}_sigma_kpc')
            if pd.isna(r_sh) or pd.isna(M_sh):
                continue
            M_enc = burkert_M_enc(r_sh, rho0, a)
            sigma_over_r = sig / r_sh if r_sh > 0 else np.nan
            rows.append({
                'Galaxy':       g['Galaxy'],
                'T':            g['T'],
                'r_kpc':        r_sh,
                'sigma_over_r': sigma_over_r,
                'M_shell':      M_sh,
                'M_enc':        M_enc,
                'hill_ratio':   M_sh / M_enc if M_enc > 0 else np.nan,
                'hill_limit':   3 * sigma_over_r**3,
            })
    return pd.DataFrame(rows)

# ============================================================================
# PANEL A — per-realization FP rate
# ============================================================================

def plot_fp_rate(ax, null_df):
    for cap, color, label, jitter in [
        (0.4, C04, r'Strict ($\sigma/r \leq 0.4$, $n \leq 2$)', -0.07),
        (0.8, C08, r'Relaxed ($\sigma/r \leq 0.8$, $n \leq 3$)', +0.07),
    ]:
        sub      = null_df[null_df['cap'] == cap]
        per_real = sub.groupby('realization')['false_positive'].mean() * 100
        xs       = np.arange(1, len(per_real) + 1) + jitter
        mean     = per_real.mean()
        std      = per_real.std()

        ax.scatter(xs, per_real, color=color, s=55, zorder=5, label=label)
        ax.axhline(mean, color=color, lw=1.6, ls='--', alpha=0.75)
        ax.axhspan(mean - std, mean + std, color=color, alpha=0.10)

        # Annotate mean
        ax.text(len(per_real) + 0.55, mean,
                f'{mean:.1f}%', color=color, fontsize=9,
                va='center', ha='left', fontweight='bold')

    n_real = null_df['realization'].nunique()
    ax.set_xlabel('Realization', fontsize=11)
    ax.set_ylabel('False-positive rate (%)', fontsize=11)
    ax.set_title('(a) Null-curve FP rate per realization', fontsize=11, pad=6)
    ax.set_xticks(range(1, n_real + 1))
    ax.set_xlim(0.5, n_real + 0.8)
    ax.set_ylim(0, max(13, null_df.groupby(['cap','realization'])
                        ['false_positive'].mean().max() * 100 * 1.4))
    ax.legend(fontsize=9, framealpha=0.9, loc='upper right')
    ax.tick_params(labelsize=10)
    ax.spines[['top', 'right']].set_visible(False)

# ============================================================================
# PANEL B — Hill criterion scatter
# ============================================================================

def plot_hill_scatter(ax, fp_df, real_df):
    # Hill criterion boundary
    sr_grid  = np.linspace(0.005, 0.88, 400)
    hill_line = 3 * sr_grid**3

    # Shaded Hill-violated zone
    ax.fill_between(sr_grid, hill_line, 1e5,
                    color='#FFCCCC', alpha=0.45, zorder=1,
                    label='Hill-violated zone')
    ax.plot(sr_grid, hill_line, color='#CC2222', lw=1.8, zorder=4,
            label=r'Hill criterion:  $M_\mathrm{sh}/M_\mathrm{enc} = 3\,(\sigma/r)^3$')

    # Cap boundary verticals
    for cap, color in [(0.4, C04), (0.8, C08)]:
        ax.axvline(cap, color=color, lw=1.2, ls=':', alpha=0.70, zorder=3)
        ax.text(cap, 0.0075,
                f'$\\sigma/r={cap}$', color=color, fontsize=8,
                ha='center', va='top', rotation=90)

    # Real shells
    ax.scatter(real_df['sigma_over_r'], real_df['hill_ratio'],
               color=CGREY, s=22, alpha=0.55, zorder=5, marker='o',
               label='Real shells (catalog)')

    # FP shells — strict cap
    fp04 = fp_df[fp_df['cap'] == 0.4]
    ax.scatter(fp04['sigma_over_r'], fp04['hill_ratio'],
               color=C04, s=38, alpha=0.85, zorder=6, marker='^',
               label='FP shells — strict cap')

    # FP shells — relaxed cap (non-surviving)
    fp08     = fp_df[fp_df['cap'] == 0.8]
    fp08_viol = fp08[fp08['hill_violated'] == 1]
    ax.scatter(fp08_viol['sigma_over_r'], fp08_viol['hill_ratio'],
               color=C08, s=38, alpha=0.85, zorder=6, marker='s',
               label='FP shells — relaxed cap')

    # Cap-pegged Hill survivors (circled)
    survivors = fp08[fp08['hill_violated'] == 0]
    if len(survivors):
        ax.scatter(survivors['sigma_over_r'], survivors['hill_ratio'],
                   color=C08, s=90, zorder=7, marker='s',
                   edgecolors='black', linewidth=1.4,
                   label=f'Hill-surviving FP (cap-pegged, $n={len(survivors)}$)')

    ax.set_yscale('log')
    ax.set_xlabel(r'Shell width  $\sigma/r$', fontsize=11)
    ax.set_ylabel(r'$M_\mathrm{shell}\;/\;M_\mathrm{enc}(<r_\mathrm{sh})$',
                  fontsize=11)
    ax.set_title('(b) Hill criterion: FP shells vs real shells',
                 fontsize=11, pad=6)
    ax.set_xlim(0, 0.90)
    ax.set_ylim(0.003, 800)
    ax.tick_params(labelsize=10)
    ax.spines[['top', 'right']].set_visible(False)
    ax.legend(fontsize=8.5, framealpha=0.9, loc='upper left')

# ============================================================================
# MAIN
# ============================================================================

def parse_args():
    p = argparse.ArgumentParser(description='Plot null injection test figure')
    p.add_argument('--null',    default=NULL_CSV,   help='Null test results CSV')
    p.add_argument('--real',    default=REAL_CSV,   help='Real catalog CSV')
    p.add_argument('--outdir',  default=OUTPUT_DIR, help='Output directory')
    p.add_argument('--no-pdf',  action='store_true', help='Skip PDF output')
    p.add_argument('--dpi',     type=int, default=200)
    return p.parse_args()


def main():
    cfg = parse_args()
    os.makedirs(cfg.outdir, exist_ok=True)

    print(f"Loading null test results from: {cfg.null}")
    null_df, fp_df = load_null(cfg.null)
    print(f"  {len(null_df)} rows  |  {fp_df['shell_idx'].notna().sum()} FP shells")

    print(f"Loading real catalog from: {cfg.real}")
    real_df = load_real_shells(cfg.real)
    print(f"  {len(real_df)} real shells")

    n_gal  = null_df['Galaxy'].nunique()
    n_real = null_df['realization'].nunique()

    # Build figure
    fig = plt.figure(figsize=(10, 4.5))
    gs  = gridspec.GridSpec(1, 2, wspace=0.38,
                             left=0.09, right=0.97, top=0.88, bottom=0.14)
    ax1 = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])

    plot_fp_rate(ax1, null_df)
    plot_hill_scatter(ax2, fp_df, real_df)

    fig.suptitle(
        f'Synthetic null-curve injection test  '
        f'($N\\!=\\!{n_real}$ realizations, {n_gal} SPARC galaxies)',
        fontsize=12, y=0.97)

    # Save
    stem = os.path.join(cfg.outdir, 'null_test_figure')
    plt.savefig(stem + '.png', dpi=cfg.dpi, bbox_inches='tight')
    print(f"  Saved: {stem}.png")

    if not cfg.no_pdf:
        plt.savefig(stem + '.pdf', bbox_inches='tight')
        print(f"  Saved: {stem}.pdf")

    plt.close()


if __name__ == '__main__':
    main()
