#!/usr/bin/env python3
"""
Relaxed-cap shell fitter with multi-BH decomposition post-processor.
Multithreaded via multiprocessing.Pool — galaxies are independent and
fit in parallel.

PART 1: Fit SPARC rotation curves with Burkert backbone + up to N shells.
  - No DGC/Hill/M_central constraints during fitting
  - Configurable sigma/r cap (default 0.8 relaxed; pass --cap 0.4 for strict)
  - BIC selects best unconstrained configuration per galaxy

PART 2: Post-process each shell to determine multi-BH interpretation.
  - For each shell: compute implied single IMBH mass via DGC scaling
  - If M_BH_single > 1% M_central: try 2..5 equal-mass IMBHs
  - Report simplest decomposition that passes the 1% M_central limit

Usage:
  python scripts/run_relaxed_caps_fits_with_BH_decomp.py
  python scripts/run_relaxed_caps_fits_with_BH_decomp.py --cap 0.4 --max-shells 2
  python scripts/run_relaxed_caps_fits_with_BH_decomp.py --workers 8

Author: Ron Bibb (generated by Claude)
Date: 2026-05-23  (multithreaded refactor)
"""

import numpy as np
import pandas as pd
from scipy.special import erf
from scipy.optimize import curve_fit
import multiprocessing as mp
import argparse
import os
import time
import warnings

# ============================================================================
# CONFIGURATION DEFAULTS
# ============================================================================

DATA_DIR      = '../Rotmod_LTG'
OUTPUT_FILE   = './data/processed/sparc_relaxed_caps_with_BH_decomp2.csv'
CATALOG_FILE  = './data/raw/sparc_sample123.csv'

G             = 4.302e-6   # kpc (km/s)^2 / M_sun
SIGMA_V_FLOOR = 1.0        # km/s

UPSILON_DISK  = 0.5
UPSILON_BULGE = 0.7

MAX_SHELLS_DEFAULT           = 5
SHELL_WIDTH_MAX_FRAC_DEFAULT = 0.8   # Relaxed cap (0.4 = strict Paper I cap)
SHELL_M_MAX                  = 1e12
SHELL_R_MAX_GRID             = [12.0, 30.0, 80.0]

DGC_LOG10_K  = -45.0 # -37.785
DGC_SLOPE    = 4.35

M_CENTRAL_FRACTION_LIMIT = 0.01   # 1% of M_central per IMBH

# ============================================================================
# PHYSICS FUNCTIONS
# ============================================================================

def baryon_squared(vg, vd, vb):
    return (vg * np.abs(vg)
            + UPSILON_DISK  * vd * np.abs(vd)
            + UPSILON_BULGE * vb * np.abs(vb))


def burkert_v2(r, rho_0, a):
    a = max(a, 1e-6)
    x = r / a
    M_enc = np.pi * rho_0 * a**3 * (
        np.log(1 + x**2) + 2 * np.log(1 + x) - 2 * np.arctan(x)
    )
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)


def shell_v2(r, M_sh, r_sh, sigma_sh):
    sigma_sh = max(sigma_sh, 1e-6)
    M_enc = 0.5 * M_sh * (1 + erf((r - r_sh) / (np.sqrt(2) * sigma_sh)))
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)


def shell_to_implied_BH(M_sh):
    if M_sh <= 0:
        return np.nan
    return 10 ** (DGC_LOG10_K + DGC_SLOPE * np.log10(M_sh))


def decompose_shell_multi_BH(M_sh, M_central):
    M_BH_single = shell_to_implied_BH(M_sh)
    for n_BH in range(1, 6):
        M_BH_each     = M_BH_single / n_BH
        central_ratio = M_BH_each / M_central
        if central_ratio <= M_CENTRAL_FRACTION_LIMIT:
            return n_BH, M_BH_each, central_ratio
    M_BH_each = M_BH_single / 5
    return 5, M_BH_each, M_BH_each / M_central

# ============================================================================
# FITTER
# ============================================================================

def fit_configuration(r, v, sig, V2_bar, n_shells, shell_width_max_frac):
    if n_shells == 0:
        def model(r, rho_0, a):
            return np.sqrt(np.maximum(V2_bar + burkert_v2(r, rho_0, a), 0))
        starts = [[3e7, 8.0], [1e7, 15.0], [1e8, 4.0], [3e6, 30.0]]
        bounds = ([1e3, 0.1], [1e10, 200.0])
        best_chi2, best_p = np.inf, None
        for p0 in starts:
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=bounds,
                                 sigma=sig, maxfev=15000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig) ** 2))
                if chi2 < best_chi2:
                    best_chi2, best_p = chi2, p
            except Exception:
                pass
        return (best_p, best_chi2) if best_p is not None else (None, np.inf)

    else:
        def model(r, *params):
            rho_0, a = params[0], params[1]
            v2 = V2_bar + burkert_v2(r, rho_0, a)
            for i in range(n_shells):
                base = 2 + 3 * i
                M_i, r_i, sf_i = params[base], params[base+1], params[base+2]
                v2 += shell_v2(r, M_i, r_i, sf_i * r_i)
            return np.sqrt(np.maximum(v2, 0))

        starts = []
        for r_max in SHELL_R_MAX_GRID:
            for rho0 in [1e7, 3e7, 1e8]:
                for a_init in [5.0, 10.0, 20.0]:
                    radii  = [(i + 1) / (n_shells + 1) * r_max for i in range(n_shells)]
                    M_init = min(3e9 * (r_max / 12.0), 1e11)
                    p0 = [rho0, a_init]
                    for r_i in radii:
                        p0.extend([M_init, r_i, 0.25])
                    starts.append((p0, r_max))

        best_chi2, best_p = np.inf, None
        for p0, r_max in starts:
            lb = [1e3, 0.1]
            ub = [1e10, 200.0]
            for _ in range(n_shells):
                lb.extend([1e6, 0.2, 0.01])
                ub.extend([SHELL_M_MAX, r_max, shell_width_max_frac])
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=(lb, ub),
                                 sigma=sig, maxfev=20000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig) ** 2))
                if chi2 < best_chi2:
                    best_chi2, best_p = chi2, np.array(p)
            except Exception:
                pass
        return (best_p, best_chi2) if best_p is not None else (None, np.inf)

# ============================================================================
# WORKER  (module-level required for multiprocessing pickling on macOS spawn)
# ============================================================================

def fit_galaxy_worker(args):
    """
    Fit one galaxy. Called by Pool.imap_unordered.
    args: (gal, T, V_flat, data_dir, max_shells, shell_width_max_frac)
    Returns result dict or None on failure.
    """
    gal, T, V_flat, data_dir, max_shells, shell_width_max_frac = args
    warnings.filterwarnings('ignore')   # Must be set per spawned process

    try:
        d      = np.loadtxt(f'{data_dir}/{gal}_rotmod.dat', comments='#')
        r_obs  = d[:, 0]
        v_obs  = d[:, 1]
        e_v    = d[:, 2]
        v_gas  = d[:, 3]
        v_disk = d[:, 4]
        v_bul  = d[:, 5]
    except Exception:
        return None

    n_pts = len(r_obs)

    log_MBH            = 8.5 + 4.4 * np.log10(max(V_flat, 1.0) / np.sqrt(2) / 200.0)
    M_central_estimate = 10 ** log_MBH

    Vbar2  = baryon_squared(v_gas, v_disk, v_bul)
    mask   = v_obs ** 2 > Vbar2
    r      = r_obs[mask]
    v      = v_obs[mask]
    sig    = np.maximum(e_v[mask], SIGMA_V_FLOOR)
    Vbar2_m = Vbar2[mask]

    if len(r) < 5:
        return None

    bic_values, params_per_n, chi2_per_n = {}, {}, {}

    for n in range(max_shells + 1):
        if len(r) - (2 + 3 * n) < 1:
            break
        p, chi2 = fit_configuration(r, v, sig, Vbar2_m, n, shell_width_max_frac)
        if p is not None and np.isfinite(chi2):
            bic_values[n]   = chi2 + (2 + 3 * n) * np.log(len(r))
            params_per_n[n] = p
            chi2_per_n[n]   = chi2
        else:
            bic_values[n] = np.nan

    valid_n = [n for n in bic_values if np.isfinite(bic_values[n])]
    if not valid_n:
        return None

    best_n      = min(valid_n, key=lambda n: bic_values[n])
    best_params = params_per_n[best_n]
    best_chi2   = chi2_per_n[best_n]
    best_chi2_r = best_chi2 / (len(r) - (2 + 3 * best_n))

    rec = {
        'Galaxy':             gal,
        'T':                  T,
        'V_flat':             V_flat,
        'n_pts':              n_pts,
        'M_central_estimate': M_central_estimate,
        'fw_best_n_shells':   best_n,
        'fw_best_bic':        bic_values[best_n],
        'fw_best_chi2':       best_chi2,
        'fw_best_chi2_red':   best_chi2_r,
        'burk_rho0':          best_params[0],
        'burk_a_kpc':         best_params[1],
    }

    for i in range(best_n):
        base     = 2 + 3 * i
        M_sh     = best_params[base]
        r_sh     = best_params[base + 1]
        sigma_sh = best_params[base + 2] * r_sh

        n_BH, M_BH_each, cr = decompose_shell_multi_BH(M_sh, M_central_estimate)

        rec[f'shell{i+1}_r_kpc']                = r_sh
        rec[f'shell{i+1}_M']                    = M_sh
        rec[f'shell{i+1}_sigma_kpc']            = sigma_sh
        rec[f'shell{i+1}_M_BH_single']          = shell_to_implied_BH(M_sh)
        rec[f'shell{i+1}_decomp_n_BH']          = n_BH
        rec[f'shell{i+1}_decomp_M_BH_each']     = M_BH_each
        rec[f'shell{i+1}_decomp_central_ratio'] = cr
        rec[f'shell{i+1}_decomp_acceptable']    = (cr <= M_CENTRAL_FRACTION_LIMIT)

    return rec

# ============================================================================
# MAIN
# ============================================================================

def parse_args():
    p = argparse.ArgumentParser(description='Relaxed-cap SPARC shell fitter (parallel)')
    p.add_argument('--cap',        type=float, default=SHELL_WIDTH_MAX_FRAC_DEFAULT,
                   help='sigma/r width cap (default 0.8; use 0.4 for strict Paper I cap)')
    p.add_argument('--max-shells', type=int,   default=MAX_SHELLS_DEFAULT,
                   help='Maximum shells per galaxy (default 5)')
    p.add_argument('--workers',    type=int,   default=max(1, os.cpu_count() - 2),
                   help='Parallel workers (default: cpu_count - 2)')
    p.add_argument('--output',     type=str,   default=OUTPUT_FILE,
                   help='Output CSV path')
    p.add_argument('--catalog',    type=str,   default=CATALOG_FILE,
                   help='Galaxy master catalog CSV')
    p.add_argument('--data-dir',   type=str,   default=DATA_DIR,
                   help='Path to Rotmod_LTG directory')
    return p.parse_args()


def main():
    cfg    = parse_args()
    master = pd.read_csv(cfg.catalog)

    args = [
        (row['Galaxy'], int(row['T']), float(row['Vflat']),
         cfg.data_dir, cfg.max_shells, cfg.cap)
        for _, row in master.iterrows()
    ]

    print(f"{'='*60}")
    print(f"  Relaxed-cap fitter  —  multithreaded")
    print(f"  Galaxies  : {len(args)}")
    print(f"  sigma/r cap: {cfg.cap}  |  max shells: {cfg.max_shells}")
    print(f"  Workers   : {cfg.workers}  |  Output: {cfg.output}")
    print(f"{'='*60}")

    t0, results, completed = time.time(), [], 0

    with mp.Pool(processes=cfg.workers) as pool:
        for rec in pool.imap_unordered(fit_galaxy_worker, args, chunksize=1):
            completed += 1
            if rec is not None:
                results.append(rec)
                print(f"  [{completed:3d}/{len(args)}] {rec['Galaxy']:20s}"
                      f"  n={int(rec['fw_best_n_shells'])}"
                      f"  chi2_r={rec['fw_best_chi2_red']:6.2f}")
            else:
                print(f"  [{completed:3d}/{len(args)}] (skipped)")

    elapsed = time.time() - t0
    print(f"\n{'='*60}")
    print(f"  {len(results)}/{len(args)} fitted in {elapsed:.1f}s"
          f"  ({elapsed/max(len(args),1):.1f}s avg/galaxy)")
    print(f"{'='*60}")

    df = (pd.DataFrame(results)
            .sort_values('Galaxy')
            .reset_index(drop=True))
    os.makedirs(os.path.dirname(cfg.output), exist_ok=True)
    df.to_csv(cfg.output, index=False)
    print(f"  Wrote {len(df)} rows -> {cfg.output}")


if __name__ == '__main__':
    mp.set_start_method('spawn', force=True)  # Safe on macOS M1; avoids fork/OpenBLAS deadlocks
    main()
