#!/usr/bin/env python3
"""
Null injection test for the relaxed-cap shell fitter.

For each SPARC galaxy:
  1. Take the strict-cap best-fit Burkert (rho0, a) as the smooth "truth"
  2. Generate N synthetic rotation curves: V_true + Gaussian(0, sigma_v)
  3. Refit each synthetic curve under BOTH caps (0.4 strict, 0.8 relaxed)
  4. Report false-positive rate, sigma/r distribution, and Hill ratio
     for any spurious shell detections

Hill ratio uses M_burkert_enclosed(r_shell) as denominator — physically
correct (not M_BH proxy). Hill criterion: M_shell / M_enc <= 3*(sigma/r)^3

Usage:
  python scripts/run_null_test.py
  python scripts/run_null_test.py --n-real 10 --workers 16
  python scripts/run_null_test.py --n-real 1 --workers 4  # quick sanity check

Author: Ron Bibb (generated by Claude)
Date: 2026-05-23
"""

import numpy as np
import pandas as pd
from scipy.special import erf
from scipy.optimize import curve_fit
import multiprocessing as mp
import argparse
import os
import time
import warnings

# ============================================================================
# CONFIGURATION
# ============================================================================

DATA_DIR      = '../Rotmod_LTG'
STRICT_CAP_CSV = 'data/processed/null_strict_cap.csv'   # Burkert params source
CATALOG_FILE  = 'data/raw/sparc_sample123.csv'
OUTPUT_FILE   = 'data/processed/null_test_results.csv'

N_REAL_DEFAULT = 5
CAPS           = [0.4, 0.8]
MAX_SHELLS     = {0.4: 2, 0.8: 5}

G             = 4.302e-6
SIGMA_V_FLOOR = 1.0
UPSILON_DISK  = 0.5
UPSILON_BULGE = 0.7
SHELL_M_MAX   = 1e12
SHELL_R_MAX_GRID = [12.0, 30.0, 80.0]

# ============================================================================
# PHYSICS
# ============================================================================

def baryon_squared(vg, vd, vb):
    return (vg*np.abs(vg)
            + UPSILON_DISK  * vd*np.abs(vd)
            + UPSILON_BULGE * vb*np.abs(vb))


def burkert_v2(r, rho_0, a):
    a = max(a, 1e-6)
    x = r / a
    M_enc = np.pi * rho_0 * a**3 * (
        np.log(1 + x**2) + 2*np.log(1 + x) - 2*np.arctan(x))
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)


def burkert_M_enc(r, rho_0, a):
    """Total Burkert enclosed mass within r (M_sun)."""
    a = max(a, 1e-6)
    x = r / a
    return np.pi * rho_0 * a**3 * (
        np.log(1 + x**2) + 2*np.log(1 + x) - 2*np.arctan(x))


def shell_v2(r, M_sh, r_sh, sigma_sh):
    sigma_sh = max(sigma_sh, 1e-6)
    M_enc = 0.5 * M_sh * (1 + erf((r - r_sh) / (np.sqrt(2) * sigma_sh)))
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)

# ============================================================================
# FITTER  (self-contained, no import from main fitter script)
# ============================================================================

def fit_configuration(r, v, sig, V2_bar, n_shells, cap):
    if n_shells == 0:
        def model(r, rho_0, a):
            return np.sqrt(np.maximum(V2_bar + burkert_v2(r, rho_0, a), 0))
        starts = [[3e7, 8.0], [1e7, 15.0], [1e8, 4.0], [3e6, 30.0]]
        bounds = ([1e3, 0.1], [1e10, 200.0])
        best_chi2, best_p = np.inf, None
        for p0 in starts:
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=bounds,
                                 sigma=sig, maxfev=15000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig)**2))
                if chi2 < best_chi2:
                    best_chi2, best_p = chi2, p
            except Exception:
                pass
        return (best_p, best_chi2) if best_p is not None else (None, np.inf)

    else:
        def model(r, *params):
            rho_0, a = params[0], params[1]
            v2 = V2_bar + burkert_v2(r, rho_0, a)
            for i in range(n_shells):
                base = 2 + 3*i
                M_i, r_i, sf_i = params[base], params[base+1], params[base+2]
                v2 += shell_v2(r, M_i, r_i, sf_i * r_i)
            return np.sqrt(np.maximum(v2, 0))

        starts = []
        for r_max in SHELL_R_MAX_GRID:
            for rho0 in [1e7, 3e7, 1e8]:
                for a_init in [5.0, 10.0, 20.0]:
                    radii = [(i+1)/(n_shells+1)*r_max for i in range(n_shells)]
                    M_init = min(3e9*(r_max/12.0), 1e11)
                    p0 = [rho0, a_init]
                    for r_i in radii:
                        p0.extend([M_init, r_i, 0.25])
                    starts.append((p0, r_max))

        best_chi2, best_p = np.inf, None
        for p0, r_max in starts:
            lb = [1e3, 0.1]
            ub = [1e10, 200.0]
            for _ in range(n_shells):
                lb.extend([1e6, 0.2, 0.01])
                ub.extend([SHELL_M_MAX, r_max, cap])
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=(lb, ub),
                                 sigma=sig, maxfev=20000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig)**2))
                if chi2 < best_chi2:
                    best_chi2, best_p = chi2, np.array(p)
            except Exception:
                pass
        return (best_p, best_chi2) if best_p is not None else (None, np.inf)

# ============================================================================
# WORKER
# ============================================================================

def null_worker(args):
    """
    Run one null-curve realization for one galaxy under one cap.
    args: (gal, T, V_flat, data_dir, rho0_true, a_true,
           M_central, cap, max_shells, realization_id, seed)
    Returns list of result dicts (one per shell, or one n=0 row).
    """
    (gal, T, V_flat, data_dir,
     rho0_true, a_true, M_central,
     cap, max_shells, real_id, seed) = args

    warnings.filterwarnings('ignore')
    rng = np.random.default_rng(seed)

    # Load real radial sampling and uncertainties
    try:
        d      = np.loadtxt(f'{data_dir}/{gal}_rotmod.dat', comments='#')
        r_obs  = d[:, 0]
        e_v    = d[:, 2]
        v_gas  = d[:, 3]
        v_disk = d[:, 4]
        v_bul  = d[:, 5]
    except Exception:
        return []

    Vbar2 = baryon_squared(v_gas, v_disk, v_bul)
    sig   = np.maximum(e_v, SIGMA_V_FLOOR)

    # Generate synthetic smooth rotation curve + noise
    V_true = np.sqrt(np.maximum(Vbar2 + burkert_v2(r_obs, rho0_true, a_true), 0))
    V_syn  = V_true + rng.normal(0.0, sig)
    V_syn  = np.maximum(V_syn, 0.1)   # keep positive

    # Apply same mask as fitter: V_obs^2 > V_bar^2
    mask   = V_syn**2 > Vbar2
    r      = r_obs[mask]
    v      = V_syn[mask]
    s      = sig[mask]
    V2m    = Vbar2[mask]

    if len(r) < 5:
        return []

    # Fit n=0..max_shells, BIC select best
    bic_vals, params_n, chi2_n = {}, {}, {}
    for n in range(max_shells + 1):
        if len(r) - (2 + 3*n) < 1:
            break
        p, chi2 = fit_configuration(r, v, s, V2m, n, cap)
        if p is not None and np.isfinite(chi2):
            bic_vals[n]  = chi2 + (2 + 3*n) * np.log(len(r))
            params_n[n]  = p
            chi2_n[n]    = chi2
        else:
            bic_vals[n] = np.nan

    valid_n = [n for n in bic_vals if np.isfinite(bic_vals[n])]
    if not valid_n:
        return []

    best_n      = min(valid_n, key=lambda n: bic_vals[n])
    best_params = params_n[best_n]
    best_chi2_r = chi2_n[best_n] / max(len(r) - (2 + 3*best_n), 1)

    base_rec = {
        'Galaxy':       gal,
        'T':            T,
        'V_flat':       V_flat,
        'cap':          cap,
        'realization':  real_id,
        'n_shells_fit': best_n,
        'chi2_r':       best_chi2_r,
        'false_positive': int(best_n > 0),
    }

    if best_n == 0:
        return [base_rec]

    # Extract spurious shell properties
    rows = []
    rho0_fit = best_params[0]
    a_fit    = best_params[1]

    for i in range(best_n):
        base     = 2 + 3*i
        M_sh     = best_params[base]
        r_sh     = best_params[base+1]
        sf       = best_params[base+2]
        sigma_sh = sf * r_sh

        # Hill ratio: M_shell / M_burkert_enclosed(r_shell)
        # Use TRUE Burkert (smooth truth, not the fit) for M_enc
        M_enc_true = burkert_M_enc(r_sh, rho0_true, a_true)
        # Also compute with baryon contribution for completeness
        # (approximate: add baryonic enclosed mass via circular velocity)
        V_bar_at_r = np.interp(r_sh, r_obs, np.sqrt(np.maximum(Vbar2, 0)))
        M_bar_enc  = V_bar_at_r**2 * r_sh / G
        M_host_enc = M_enc_true + M_bar_enc

        hill_ratio   = M_sh / M_host_enc if M_host_enc > 0 else np.inf
        hill_limit   = 3 * sf**3          # 3*(sigma/r)^3 — Hill threshold
        hill_violated = hill_ratio > hill_limit

        rec = {**base_rec,
               'shell_idx':      i + 1,
               'r_kpc':          r_sh,
               'sigma_kpc':      sigma_sh,
               'sigma_over_r':   sf,
               'M_shell':        M_sh,
               'M_host_enc':     M_host_enc,
               'hill_ratio':     hill_ratio,
               'hill_limit':     hill_limit,
               'hill_violated':  int(hill_violated)}
        rows.append(rec)

    return rows

# ============================================================================
# MAIN
# ============================================================================

def parse_args():
    p = argparse.ArgumentParser(description='Null injection test for shell fitter')
    p.add_argument('--n-real',   type=int, default=N_REAL_DEFAULT,
                   help='Realizations per galaxy (default 5)')
    p.add_argument('--workers',  type=int, default=max(1, os.cpu_count() - 2),
                   help='Parallel workers (default: cpu_count - 2)')
    p.add_argument('--output',   type=str, default=OUTPUT_FILE)
    p.add_argument('--data-dir', type=str, default=DATA_DIR)
    p.add_argument('--catalog',  type=str, default=CATALOG_FILE)
    p.add_argument('--burkert',  type=str, default=STRICT_CAP_CSV,
                   help='CSV with burk_rho0 and burk_a_kpc columns')
    p.add_argument('--seed',     type=int, default=42,
                   help='Base random seed (per-task seeds are derived from this)')
    return p.parse_args()


def main():
    cfg = parse_args()

    master  = pd.read_csv(cfg.catalog)
    burkert = pd.read_csv(cfg.burkert)[['Galaxy','burk_rho0','burk_a_kpc',
                                         'M_central_estimate']].dropna()
    master  = master.merge(burkert, on='Galaxy', how='inner')

    print(f"{'='*62}")
    print(f"  Null injection test")
    print(f"  Galaxies     : {len(master)}")
    print(f"  Realizations : {cfg.n_real} per galaxy")
    print(f"  Caps tested  : {CAPS}")
    print(f"  Workers      : {cfg.workers}")
    print(f"  Total tasks  : {len(master) * cfg.n_real * len(CAPS)}")
    print(f"{'='*62}")

    # Build task list
    tasks = []
    for _, row in master.iterrows():
        for cap in CAPS:
            for r_id in range(cfg.n_real):
                seed = cfg.seed + hash((row['Galaxy'], cap, r_id)) % (2**31)
                tasks.append((
                    row['Galaxy'], int(row['T']), float(row['Vflat']),
                    cfg.data_dir,
                    float(row['burk_rho0']), float(row['burk_a_kpc']),
                    float(row['M_central_estimate']),
                    cap, MAX_SHELLS[cap], r_id, int(seed)
                ))

    t0, all_rows, done = time.time(), [], 0

    with mp.Pool(processes=cfg.workers) as pool:
        for result in pool.imap_unordered(null_worker, tasks, chunksize=1):
            done += 1
            all_rows.extend(result)
            if done % 20 == 0 or done == len(tasks):
                elapsed = time.time() - t0
                eta = elapsed / done * (len(tasks) - done)
                print(f"  [{done:4d}/{len(tasks)}]  "
                      f"rows so far: {len(all_rows):5d}  "
                      f"elapsed: {elapsed:5.0f}s  ETA: {eta:5.0f}s")

    df = pd.DataFrame(all_rows).sort_values(
        ['Galaxy','cap','realization','shell_idx']).reset_index(drop=True)
    os.makedirs(os.path.dirname(cfg.output), exist_ok=True)
    df.to_csv(cfg.output, index=False)

    elapsed = time.time() - t0
    print(f"\n{'='*62}")
    print(f"  Completed in {elapsed:.0f}s  ({elapsed/len(tasks):.1f}s/task)")
    print(f"  Rows written: {len(df)}")
    print(f"  Output: {cfg.output}")
    print(f"{'='*62}")

    # Quick summary
    gal_cap = df.groupby(['Galaxy','cap']).agg(
        false_positive=('false_positive','max')).reset_index()
    for cap in CAPS:
        sub = gal_cap[gal_cap['cap']==cap]
        fp_rate = sub.groupby('Galaxy')['false_positive'].max()
        fp_any  = (fp_rate > 0).mean() * 100
        print(f"\n  Cap={cap}: FP rate (any realization) = {fp_any:.1f}%")

    fp_shells = df[df['false_positive']==1].dropna(subset=['hill_ratio'])
    if len(fp_shells):
        print(f"\n  False-positive shells — Hill violation summary:")
        for cap in CAPS:
            sub = fp_shells[fp_shells['cap']==cap]
            if len(sub) == 0: continue
            viol = (sub['hill_violated']==1).mean()*100
            print(f"    cap={cap}: {len(sub)} FP shells, "
                  f"{viol:.1f}% Hill-violated  "
                  f"(median hill_ratio={sub['hill_ratio'].median():.4f}, "
                  f"hill_limit={sub['hill_limit'].median():.4f})")


if __name__ == '__main__':
    mp.set_start_method('spawn', force=True)
    main()
