#!/usr/bin/env python3
"""
Relaxed-cap shell fitter with multi-BH decomposition post-processor.

PART 1: Fit SPARC rotation curves with Burkert backbone + up to 5 shells.
  - No DGC/Hill/M_central constraints during fitting
  - Relaxed σ/r cap at 0.8 (allow wider shells than strict 0.4)
  - BIC selects best unconstrained configuration per galaxy

PART 2: Post-process each shell to determine multi-BH interpretation.
  - For each shell: compute what single IMBH would have that mass (DGC)
  - If M_BH_single > 1% M_central: decompose into 2, 3, 4, 5 equal-mass IMBHs
  - Report the simplest solution that passes 1% M_central constraint
  - Track multi-BH interpretation in output CSV

Author: Ron Bibb (generated by Claude)
Date: 2026-05-22
"""

import numpy as np
import pandas as pd
from scipy.special import erf
from scipy.optimize import curve_fit
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# CONFIGURATION
# ============================================================================

DATA_DIR = '/Users/ronbibb/Library/CloudStorage/OneDrive-Personal(2)/Documents/Academic/Rotmod_LTG'
OUTPUT_FILE = 'sparc_relaxed_caps_with_BH_decomp.csv'

# Physical parameters
G = 4.302e-6  # kpc (km/s)^2 / M_sun
SIGMA_V_FLOOR = 1.0  # km/s

# Disk/bulge mass-to-light ratios (Upsilon)
UPSILON_DISK = 0.5
UPSILON_BULGE = 0.7

# Shell fitting
MAX_SHELLS = 5
SHELL_WIDTH_MAX_FRAC = 0.8  # Relaxed cap (was 0.4 in strict run)
SHELL_M_MAX = 1e12
SHELL_R_MAX_GRID = [12.0, 30.0, 80.0]

# DGC scaling (Davis, Graham & Combes 2019)
DGC_LOG10_K = -37.785
DGC_SLOPE = 4.35

# M_central limit for multi-BH acceptance
M_CENTRAL_FRACTION_LIMIT = 0.01  # 1%

# ============================================================================
# CORE FUNCTIONS
# ============================================================================

def baryon_squared(vg, vd, vb):
    """Compute V_baryon^2 from gas, disk, bulge contributions."""
    return vg*np.abs(vg) + UPSILON_DISK*vd*np.abs(vd) + UPSILON_BULGE*vb*np.abs(vb)

def burkert_v2(r, rho_0, a):
    """Burkert profile velocity^2."""
    a = max(a, 1e-6)
    x = r / a
    M_enc = np.pi * rho_0 * a**3 * (
        np.log(1 + x**2) + 2*np.log(1+x) - 2*np.arctan(x)
    )
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)

def shell_v2(r, M_sh, r_sh, sigma_sh):
    """Shell (Gaussian profile) velocity^2."""
    sigma_sh = max(sigma_sh, 1e-6)
    M_enc = 0.5 * M_sh * (1 + erf((r - r_sh) / (np.sqrt(2) * sigma_sh)))
    return np.maximum(G * M_enc / np.maximum(r, 1e-6), 0)

def fit_configuration(r, v, sig, V2_bar, n_shells):
    """
    Fit Burkert + n_shells using multiple starting configurations.
    Returns (params, chi2) or (None, np.inf) if fitting fails.
    """
    if n_shells == 0:
        # Burkert-only fit
        def model(r, rho_0, a):
            return np.sqrt(np.maximum(V2_bar + burkert_v2(r, rho_0, a), 0))
        starts = [[3e7, 8.0], [1e7, 15.0], [1e8, 4.0], [3e6, 30.0]]
        bounds = ([1e3, 0.1], [1e10, 200.0])
        best_chi2 = np.inf
        best_p = None
        for p0 in starts:
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=bounds, sigma=sig, maxfev=15000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig)**2))
                if chi2 < best_chi2:
                    best_chi2 = chi2
                    best_p = p
            except:
                continue
        return best_p, best_chi2 if best_p is not None else (None, np.inf)
    
    else:
        # Burkert + n_shells joint fit
        def model(r, *params):
            rho_0, a = params[0], params[1]
            v2 = V2_bar + burkert_v2(r, rho_0, a)
            for i in range(n_shells):
                base = 2 + 3*i
                M_i, r_i, sf_i = params[base], params[base+1], params[base+2]
                sigma_i = sf_i * r_i
                v2 = v2 + shell_v2(r, M_i, r_i, sigma_i)
            return np.sqrt(np.maximum(v2, 0))
        
        # Multi-start with various r_max and init params
        starts = []
        for r_max in SHELL_R_MAX_GRID:
            for rho0 in [1e7, 3e7, 1e8]:
                for a_init in [5.0, 10.0, 20.0]:
                    radii = [(i+1)/(n_shells+1)*r_max for i in range(n_shells)]
                    M_init = min(3e9 * (r_max/12.0), 1e11)
                    p0 = [rho0, a_init]
                    for r_i in radii:
                        p0.extend([M_init, r_i, 0.25])
                    starts.append((p0, r_max))
        
        best_chi2 = np.inf
        best_p = None
        for p0, r_max in starts:
            lb = [1e3, 0.1]
            ub = [1e10, 200.0]
            for i in range(n_shells):
                lb.extend([1e6, 0.2, 0.01])
                ub.extend([SHELL_M_MAX, r_max, SHELL_WIDTH_MAX_FRAC])
            try:
                p, _ = curve_fit(model, r, v, p0=p0, bounds=(lb, ub), 
                                sigma=sig, maxfev=20000)
                chi2 = float(np.sum(((v - model(r, *p)) / sig)**2))
                if chi2 < best_chi2:
                    best_chi2 = chi2
                    best_p = np.array(p)
            except:
                continue
        
        return best_p, best_chi2 if best_p is not None else (None, np.inf)

def shell_to_implied_BH(M_sh):
    """Convert shell mass to implied single IMBH mass via DGC scaling."""
    if M_sh <= 0:
        return np.nan
    return 10**(DGC_LOG10_K + DGC_SLOPE * np.log10(M_sh))

def decompose_shell_multi_BH(M_sh, M_central):
    """
    For a shell of mass M_sh, find the simplest multi-BH decomposition
    that passes the 1% M_central limit.
    
    Returns (n_BH, M_BH_each, central_ratio)
    """
    M_BH_single = shell_to_implied_BH(M_sh)
    
    # Try n_BH from 1 to 5
    for n_BH in range(1, 6):
        M_BH_each = M_BH_single / n_BH
        central_ratio = M_BH_each / M_central
        if central_ratio <= M_CENTRAL_FRACTION_LIMIT:
            return n_BH, M_BH_each, central_ratio
    
    # If nothing works, return the 5-BH case (may exceed limit, flag it)
    n_BH = 5
    M_BH_each = M_BH_single / n_BH
    central_ratio = M_BH_each / M_central
    return n_BH, M_BH_each, central_ratio

# ============================================================================
# MAIN LOOP
# ============================================================================

def main():
    """Fit all SPARC galaxies and post-process for multi-BH decompositions."""
    
    # Load master catalog
    master = pd.read_csv('../data/sparc_sample123.csv')
    galaxies = master['Galaxy'].values
    
    results = []
    
    for gal in galaxies:
        # Load rotation curve
        try:
            d = np.loadtxt(f'{DATA_DIR}/{gal}_rotmod.dat', comments='#')
            r_obs = d[:, 0]
            v_obs = d[:, 1]
            e_v = d[:, 2]
            v_gas = d[:, 3]
            v_disk = d[:, 4]
            v_bul = d[:, 5]
        except:
            continue
        
        # Get galaxy properties
        gal_row = master[master['Galaxy'] == gal].iloc[0]
        T = int(gal_row['T'])
        V_flat = gal_row['Vflat']
        n_pts = len(r_obs)
        
        # Estimate M_central (Kormendy & Ho 2013)
        log_MBH = 8.5 + 4.4 * np.log10(V_flat / np.sqrt(2) / 200.0)
        M_central_estimate = 10**log_MBH
        
        # Prepare for fitting
        Vbar2 = baryon_squared(v_gas, v_disk, v_bul)
        mask = v_obs**2 > Vbar2
        r = r_obs[mask]
        v = v_obs[mask]
        sig = np.maximum(e_v[mask], SIGMA_V_FLOOR)
        Vbar2_m = Vbar2[mask]
        
        if len(r) < 5:
            continue
        
        # Fit each n_shells from 0 to MAX_SHELLS
        bic_values = {}
        params_per_n = {}
        chi2_per_n = {}
        
        for n in range(MAX_SHELLS + 1):
            dof = len(r) - (2 + 3*n)
            if dof < 1:
                break
            
            p, chi2 = fit_configuration(r, v, sig, Vbar2_m, n)
            if p is None or not np.isfinite(chi2):
                bic_values[n] = np.nan
            else:
                bic = chi2 + (2 + 3*n) * np.log(len(r))
                bic_values[n] = bic
                params_per_n[n] = p
                chi2_per_n[n] = chi2
        
        # Select best n_shells by BIC
        valid_n = [n for n in bic_values if np.isfinite(bic_values[n])]
        if not valid_n:
            continue
        
        best_n = min(valid_n, key=lambda n: bic_values[n])
        best_params = params_per_n[best_n]
        best_chi2 = chi2_per_n[best_n]
        best_bic = bic_values[best_n]
        best_chi2_r = best_chi2 / (len(r) - (2 + 3*best_n))
        
        # Extract parameters
        rho0_burk = best_params[0]
        a_burk = best_params[1]
        
        # Record base info
        rec = {
            'Galaxy': gal,
            'T': T,
            'V_flat': V_flat,
            'n_pts': n_pts,
            'M_central_estimate': M_central_estimate,
            'fw_best_n_shells': best_n,
            'fw_best_bic': best_bic,
            'fw_best_chi2': best_chi2,
            'fw_best_chi2_red': best_chi2_r,
            'burk_rho0': rho0_burk,
            'burk_a_kpc': a_burk,
        }
        
        # Add shell info and multi-BH decomposition
        for i in range(best_n):
            base = 2 + 3*i
            M_sh = best_params[base]
            r_sh = best_params[base+1]
            sigma_frac = best_params[base+2]
            sigma_sh = sigma_frac * r_sh
            
            n_BH, M_BH_each, cr = decompose_shell_multi_BH(M_sh, M_central_estimate)
            
            rec[f'shell{i+1}_r_kpc'] = r_sh
            rec[f'shell{i+1}_M'] = M_sh
            rec[f'shell{i+1}_sigma_kpc'] = sigma_sh
            rec[f'shell{i+1}_M_BH_single'] = shell_to_implied_BH(M_sh)
            rec[f'shell{i+1}_decomp_n_BH'] = n_BH
            rec[f'shell{i+1}_decomp_M_BH_each'] = M_BH_each
            rec[f'shell{i+1}_decomp_central_ratio'] = cr
            rec[f'shell{i+1}_decomp_acceptable'] = (cr <= M_CENTRAL_FRACTION_LIMIT)
        
        results.append(rec)
        print(f"{gal}: n={best_n}, chi2_r={best_chi2_r:.2f}")
    
    # Write output
    df = pd.DataFrame(results)
    df.to_csv(OUTPUT_FILE, index=False)
    print(f"\nWrote {len(df)} galaxies to {OUTPUT_FILE}")

if __name__ == '__main__':
    main()